# The settings that are auto-generated by the installer
settings:
# Returns a normal module
{ pkgs, lib, ... }:
{
  programs.nix-index.enable = true;
  programs.command-not-found.enable = false;

  programs.home-manager.enable = true;

  programs.autojump.enable = true;

  programs.direnv.enable = true;
  programs.direnv.nix-direnv.enable = true;

  programs.zsh.enable = true;
  programs.bash.enable = true;

  home = {
    inherit (settings) username homeDirectory;
    packages = with pkgs; [
      nixpkgs-fmt

      nodejs

      pstree
      rsync
      sqlite-interactive
      tree
    ];
  };
}
